version: "3"

services:
  bot:
    build: .
    restart: unless-stopped
    container_name: coders-bot
    links:
      - "lavalink"

  lavalink:
    build:
      context: ./lavalink
    env_file: .env
    restart: unless-stopped
    container_name: coders-bot-lavalink
    volumes:
      - ./lavalink:/opt/lavalink
